spring:
  application:
    name: api-gateway-throttling
  threads:
    virtual:
      enabled: true

management:
  endpoint:
    caches:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'